AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  apigatewaysample

  Sample SAM Template for apigatewaysample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # 全Lambdaの共通の設定
    Timeout: 5
    Runtime: python3.12
    Handler: app.lambda_handler

Resources:
  # API Gatewayの設定
  SampleApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: apigatewaysample-api
      StageName: Prod
      OpenApiVersion: 3.1.0
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: docs/openapi.yaml

  # 各LambdaとAPI Gatewayの紐づけ
  SapmleListFunction:
    Type: AWS::Serverless::Function
    Properties:
      # 紐づけるLambdaのディレクトリ
      CodeUri: lambda/sample_list/
      # 紐づけるURLパスとメソッド
      Events:
        SampleList:
          Type: Api 
          Properties:
            Path: /samples
            Method: get
            RestApiId:
              Ref: SampleApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SampleApi:
    Description: "API Gateway endpoint URL for Prod stage for SampleApi"
    Value: !Sub "https://${SampleApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
