openapi: 3.1.0
info:
  title: API Gatewayサンプル
  version: 1.0.0
paths:
  /samples:
    get:
      summary: 一覧データを取得する
      responses:
        '200':
          description: 一覧データを取得する
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sample'

components:
  schemas:
    Sample:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
